### ISSUE TITLE
Install over ArgoCDExtension

### ISSUE THREAD

**Issue by batazor** [crumbhole/argocd-lovely-plugin#98] opened 2023-01-18 17:53 UTC
At the moment, is it possible to install a plugin via ArgoCDExtension? I understand that configManagementPlugins is a deprecated parameter and will soon be removed https://github.com/argoproj/argo-helm/discussions/1766

**Comment by tico24** [comment] 2023-01-19 07:45
So the successor to configManagementPlugins is the confusingly-named CMP sidecar plugin. We are working towards that... the CI is already updated to build the images, we just need to work to make them more CMP sidecar friendly. This will be done before the old-school configManagementPlugin option is removed from Argo CD. Follow #73 to keep updated on this.

ArgoCDExtensions appears to be a UI extension capability and we have no current plans to support that, nor is that what I think you actually want.

I'll close this issue off as a duplicate of #73

**Closed by tico24** 2023-01-19 07:45 UTC
